# Statements: control flow, error handling, assignment forms, file I/O, misc.
def S(body, decl=""):
    return f"{decl}\nSub Form_Load ()\n{body}\nEnd Sub\n"

B = [
 ("If single line", "    If a = 1 Then b = 2"),
 ("If single line Else", "    If a = 1 Then b = 2 Else b = 3"),
 ("If block", "    If a = 1 Then\n        b = 2\n    End If"),
 ("If ElseIf Else", "    If a = 1 Then\n        b = 2\n    ElseIf a = 2 Then\n        b = 3\n    ElseIf a = 3 Then\n        b = 4\n    Else\n        b = 5\n    End If"),
 ("nested If", "    If a Then\n        If b Then\n            c = 1\n        Else\n            c = 2\n        End If\n    End If"),
 ("If with And Or Not", "    If a = 1 And b <> 2 Or Not c Then d = 1"),
 ("Select Case values", "    Select Case a\n        Case 1\n            b = 1\n        Case 2, 3\n            b = 2\n        Case Else\n            b = 3\n    End Select"),
 ("Select Case To Is", "    Select Case a\n        Case 1 To 5\n            b = 1\n        Case Is > 10\n            b = 2\n        Case Is <= -1, 7\n            b = 3\n    End Select"),
 ("Select Case strings", '    Select Case s$\n        Case "a"\n            b = 1\n        Case "b" To "d"\n            b = 2\n    End Select'),
 ("For Next", "    For i = 1 To 10\n        a = a + i\n    Next i"),
 ("For Step negative", "    For i = 10 To 1 Step -2\n        a = a + i\n    Next"),
 ("For nested Next i, j", "    For i = 1 To 3\n        For j = 1 To 3\n            a = a + i * j\n    Next j, i"),
 ("For Exit For", "    For i = 1 To 10\n        If i = 5 Then Exit For\n    Next i"),
 ("For Single var", "    For x! = 0 To 1 Step .25\n        a = a + x!\n    Next"),
 ("Do While Loop", "    Do While a < 10\n        a = a + 1\n    Loop"),
 ("Do Until Loop", "    Do Until a >= 10\n        a = a + 1\n    Loop"),
 ("Do Loop While", "    Do\n        a = a + 1\n    Loop While a < 10"),
 ("Do Loop Until", "    Do\n        a = a + 1\n    Loop Until a >= 10"),
 ("Do Exit Do", "    Do\n        a = a + 1\n        If a > 5 Then Exit Do\n    Loop"),
 ("While Wend", "    While a < 10\n        a = a + 1\n    Wend"),
 ("GoTo label", "    GoTo Lbl\n    a = 1\nLbl:\n    b = 2"),
 ("GoTo line number", "    GoTo 100\n    a = 1\n100 b = 2"),
 ("GoSub Return", "    GoSub Sr\n    Exit Sub\nSr:\n    a = 1\n    Return"),
 ("On GoTo", "    On a GoTo L1, L2\nL1:\n    b = 1\nL2:\n    b = 2"),
 ("On GoSub", "    On a GoSub L1, L2\n    Exit Sub\nL1:\n    Return\nL2:\n    Return"),
 ("On Error GoTo", "    On Error GoTo Eh\n    a = 1 / 0\n    Exit Sub\nEh:\n    Resume Next"),
 ("On Error Resume Next", "    On Error Resume Next\n    a = 1 / 0"),
 ("On Error GoTo 0", "    On Error GoTo 0"),
 ("Resume label", "    On Error GoTo Eh\n    a = 1\n    Exit Sub\nEh:\n    Resume Done\nDone:\n    b = 1"),
 ("Resume 0", "    On Error GoTo Eh\n    a = 1\n    Exit Sub\nEh:\n    Resume"),
 ("Error statement", "    Error 5"),
 ("Err = 0", "    Err = 0"),
 ("Let explicit", "    Let a = 1"),
 ("Mid$ statement", '    s$ = "hello"\n    Mid$(s$, 2, 2) = "xy"'),
 ("LSet RSet", '    Dim s As String * 8\n    LSet s = "ab"\n    RSet s = "cd"'),
 ("Swap-like temp", "    t = a: a = b: b = t"),
 ("colon statements", "    a = 1: b = 2: c = 3"),
 ("Exit Sub", "    If a Then Exit Sub\n    b = 1"),
 ("End", "    If a Then End"),
 ("Stop", "    If a Then Stop"),
 ("Beep DoEvents", "    Beep\n    x = DoEvents()"),
 ("Randomize", "    Randomize\n    Randomize 5"),
 ("Open Close Output", '    Open "c:\\t.txt" For Output As #1\n    Print #1, "a"; 1\n    Write #1, "b", 2\n    Close #1'),
 ("Open Input Line Input", '    Open "c:\\t.txt" For Input As #2\n    Line Input #2, s$\n    Input #2, a, b\n    Close'),
 ("Open Append", '    Open "c:\\t.txt" For Append As 3\n    Print #3, a\n    Close 3'),
 ("Open Binary Get Put", '    Open "c:\\t.bin" For Binary As #1\n    Get #1, 1, a%\n    Put #1, , a%\n    Seek #1, 5\n    Close #1'),
 ("Open Random Len", '    Open "c:\\t.dat" For Random As #1 Len = 10\n    Get #1, 2, s$\n    Close #1'),
 ("Open Access Lock", '    Open "c:\\t.dat" For Binary Access Read Lock Write As #1\n    Close #1'),
 ("FreeFile EOF LOF", '    f = FreeFile\n    Open "c:\\t.txt" For Input As f\n    Do Until EOF(f)\n        Line Input #f, s$\n    Loop\n    n = LOF(f)\n    Close f'),
 ("Kill Name MkDir", '    Kill "c:\\a.txt"\n    Name "c:\\b" As "c:\\c"\n    MkDir "c:\\d"\n    RmDir "c:\\d"\n    ChDir "c:\\"\n    ChDrive "c"'),
 ("Print# Tab Spc", '    Print #1, Tab(5); "a"; Spc(3); "b"'),
 ("Width #", "    Width #1, 80"),
 ("Debug.Print forms", '    Debug.Print\n    Debug.Print a;\n    Debug.Print a, b\n    Debug.Print "x"; Tab(3); "y"'),
 ("SendKeys AppActivate", '    SendKeys "{ENTER}", True\n    AppActivate "Notepad"'),
 ("Shell", '    x = Shell("notepad.exe", 1)'),
 ("Load Unload Show Hide", "    Load @SELF@\n    @SELF@.Show\n    @SELF@.Hide\n    Unload @SELF@"),
 ("Show modal", "    @SELF@.Show 1"),
 ("MsgBox statement and function", '    MsgBox "hi"\n    MsgBox "hi", 48, "t"\n    r = MsgBox("q", 36)'),
 ("Date$ Time$ assignment", '    Date$ = "01-01-1994"\n    Time$ = "10:00:00"'),
]
cases = [dict(name=n, code=S(b)) for n, b in B]
cases += [
    dict(name="Sub args ByVal ByRef", code="Sub P1 (ByVal a As Integer, b As Long, c$, d())\n    a = 1\nEnd Sub\n" + S("    Static arr(3)\n    P1 1, 2, \"x\", arr()")),
    dict(name="Function return types", code="Function F1% (a)\n    F1% = a\nEnd Function\nFunction F2 (a) As Double\n    F2 = a\nEnd Function\n" + S("    x = F1%(1) + F2(2)")),
    dict(name="Exit Function", code="Function F1 (a)\n    If a Then Exit Function\n    F1 = 2\nEnd Function\n" + S("    x = F1(0)")),
    dict(name="recursion", code="Function Fac (n)\n    If n <= 1 Then Fac = 1 Else Fac = n * Fac(n - 1)\nEnd Function\n" + S("    x = Fac(5)")),
    dict(name="Static local vars", code=S("    Static cnt As Integer, s As String\n    cnt = cnt + 1")),
    dict(name="Static Function", code="Static Function Cnt ()\n    n = n + 1\n    Cnt = n\nEnd Function\n" + S("    x = Cnt()")),
    dict(name="Option Compare Text", code="Option Compare Text\n" + S('    If "a" = "A" Then b = 1')),
    dict(name="Option Base 1", code="Option Base 1\nDim a(5)\n" + S("    a(1) = 1")),
    dict(name="Line Input Variant", code=S('    Open "c:\\t.txt" For Input As #2\n    Line Input #2, v\n'
                                            '    Line Input #2, w(a)\n    Close', "Dim v, w(3)")),
    dict(name="Option Explicit all declared", code="Option Explicit\nDim a As Integer\n" + S("    Dim b\n    a = 1: b = 2")),
]
