# Statements and constructs, one Sub each.
header = "Dim a, b, s$, x!, d#, l&, c@, i%, j%, arr(3)\n"
lines = [
 ("Case To", "Select Case a\nCase 1 To 5\nEnd Select"),
 ("Case Is <=", "Select Case a\nCase Is <= -1\nEnd Select"), ("Case Is >", "Select Case a\nCase Is > 9\nEnd Select"),
 ("Case Is =", "Select Case a\nCase Is = 3\nEnd Select"), ("Case Is <>", "Select Case a\nCase Is <> 3\nEnd Select"),
 ("Case Is <", "Select Case a\nCase Is < 3\nEnd Select"), ("Case Is >=", "Select Case a\nCase Is >= 3\nEnd Select"),
 ("Case list", "Select Case a\nCase 1, 7\nEnd Select"), ("Case Else", "Select Case a\nCase 1\nCase Else\nEnd Select"),
 ("Select$ =", 'Select Case s$\nCase "b"\nEnd Select'), ("Select$ To", 'Select Case s$\nCase "b" To "d"\nEnd Select'),
 ("Select$ Is >", 'Select Case s$\nCase Is > "x"\nEnd Select'),
 ("Select% To", "Select Case i%\nCase 1 To 5\nEnd Select"), ("Select% Is", "Select Case i%\nCase Is > 5\nEnd Select"),
 ("For!", "For x! = 0 To 1 Step .25\nNext"), ("For#", "For d# = 0 To 1\nNext"), ("For&", "For l& = 0 To 1\nNext"),
 ("For@", "For c@ = 0 To 1\nNext"), ("ForV", "For a = 0 To 1\nNext"), ("For% Step", "For i% = 0 To 9 Step 2\nNext i%"),
 ("Next j, i", "For i% = 1 To 2\nFor j% = 1 To 2\nNext j%, i%"),
 ("Loop While", "Do\nLoop While a < 10"), ("Loop Until", "Do\nLoop Until a < 10"), ("Do While", "Do While a\nLoop"),
 ("Do Until", "Do Until a\nLoop"), ("While Wend", "While a\nWend"), ("Exit Do", "Do\nExit Do\nLoop"),
 ("Exit For", "For i% = 1 To 2\nExit For\nNext"),
 ("On GoTo", "On a GoTo L1, L2\nL1:\nL2:"), ("On GoSub", "On a GoSub L1, L2\nL1:\nL2:"),
 ("Let", "Let a = 1"), ("Mid$ stmt 3", 'Mid$(s$, 2, 2) = "xy"'), ("Mid$ stmt 2", 'Mid$(s$, 2) = "xy"'),
 ("LSet", 'LSet s$ = "ab"'), ("RSet", 'RSet s$ = "cd"'), ("Stop", "Stop"), ("Randomize n", "Randomize 5"),
 ("Write#", 'Write #1, "b", 2'), ("Write# empty", "Write #1,"), ("Write# 1", "Write #1, a"), ("Line Input#", "Line Input #2, s$"),
 ("Name", 'Name "c:\\b" As "c:\\c"'), ("MkDir", 'MkDir "c:\\d"'), ("RmDir", 'RmDir "c:\\d"'), ("Kill", 'Kill "c:\\x"'),
 ("Width#", "Width #1, 80"), ("SendKeys wait", 'SendKeys "{ENTER}", True'), ("SendKeys", 'SendKeys "a"'),
 ("AppActivate", 'AppActivate "Notepad"'), ("Date$=", 'Date$ = "01-01-1994"'), ("Time$=", 'Time$ = "10:00:00"'),
 ("End", "End"), ("Reset", "Reset"), ("Lock", "Lock #1"), ("Unlock", "Unlock #1"), ("Lock rec", "Lock #1, 3"),
 ("Seek stmt", "Seek #1, 5"), ("Error n", "Error 5"), ("Erase", "Erase arr"), ("SetAttr", 'SetAttr "c:\\x", 1'),
 ("Load", "Load START"), ("Unload", "Unload START"), ("Close all", "Close"), ("Close 2", "Close #1, #2"),
 ("Input#", "Input #1, a, b"), ("Get#", "Get #1, 1, a"), ("Put#", "Put #1, 1, a"), ("Get# norec", "Get #1, , a"),
 ("Open Append", 'Open "x" For Append As #1'), ("Open Binary", 'Open "x" For Binary As #1'),
 ("Open Random Len", 'Open "x" For Random As #1 Len = 10'), ("Open Access", 'Open "x" For Binary Access Read Write As #1'),
 ("Open Lock", 'Open "x" For Binary Shared As #1'), ("Open Lock Read", 'Open "x" For Input Lock Read As #1'),
 ("Date=", 'Date = "1/1/94"'), ("Time=", 'Time = "10:00"'), ("On Error Resume Next", "On Error Resume Next"),
 ("On Error GoTo 0", "On Error GoTo 0"), ("On Error GoTo L", "On Error GoTo L1\nL1:"),
 ("Resume Next", "Resume Next"), ("Resume 0", "Resume 0"), ("Resume L", "Resume L1\nL1:"),
 ("GoTo line#", "GoTo 10\n10 a = 1"), ("GoSub Return", "GoSub L1\nL1:\nReturn"),
]
